apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mysql-sts
  namespace: vela-demo-env
spec:
  components:
    - name: mysql
      type: statefulset
      properties:
        replicas: 3
        image: quay.io/garycncf/mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 'password'
        port: 3306
        dataMountPath: /var/lib/mysql
        storageSize: 10
        storageClassName: standard
