apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velaux
  namespace: vela-system
spec:
  ingressClassName: nginx
  rules:
  - host: kubevela.stduser<xx>.ocplab.cn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velaux
            port:
              number: 80
