apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  name: custom-trait-ingress-new
  namespace: vela-system
spec:
  podDisruptive: false
  schematic:
    cue:
      template: |
        outputs: service: {
          apiVersion: "v1"
          kind:       "Service"
          metadata: name: context.name
          spec: {
            selector: "app.oam.dev/component": context.name
            ports: [
              for k, v in parameter.http {
        	port:       v
        	targetPort: v
              },
            ]
          }
        }
        outputs: ingress: {
          apiVersion: "networking.k8s.io/v1"
          kind:       "Ingress"
          metadata: name: context.name
          spec: {
            ingressClassName: "default"
            rules: [{
              host: parameter.domain
              http: paths: [
                for k, v in parameter.http {
        	  path: k
                  pathType: "Prefix"
        	  backend: {
        	    service: {
                      name: context.name
        	      port: number: v
                    }
        	  }
                },
              ]
            }]
          }
        }
        parameter: {
          domain: string
          http: [string]: int
        } 

