apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: testapp-custom-ingress
  namespace: vela-demo-env
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        cmd:
          - node
          - server.js
        image: quay.io/oamdev/testapp:v1
        port: 8080
      traits:
        - type: custom-trait-ingress-new
          properties:
            domain: "test.my.domain"
            http:
              "/api": 8080
        - type: patch-ingressclass-for-trait
          properties:
            ingressClass: "nginx"
